export const navItems = [
  { label: 'Services', href: '#services' },
  { label: 'Solutions', href: '#solutions' },
  { label: 'About', href: '#about' },
  { label: 'Contact', href: '#contact' },
]

export const services = [
  {
    id: 1,
    title: 'Web Development',
    description: 'Custom, scalable web solutions with cutting-edge technologies and modern frameworks.',
    iconName: 'Code2',
    color: 'from-violet-600 to-purple-600',
  },
  {
    id: 2,
    title: 'Mobile Apps',
    description: 'Native and cross-platform mobile applications that engage and delight users.',
    iconName: 'Smartphone',
    color: 'from-fuchsia-600 to-pink-600',
    delay: 0.1,
  },
  {
    id: 3,
    title: 'Cloud Solutions',
    description: 'Scalable cloud infrastructure and seamless deployment optimization.',
    iconName: 'Cloud',
    color: 'from-cyan-500 to-blue-600',
    delay: 0.2,
  },
  {
    id: 4,
    title: 'AI Integration',
    description: 'Machine learning and AI-powered intelligent automation systems.',
    iconName: 'Zap',
    color: 'from-amber-500 to-orange-600',
    delay: 0.3,
  },
  {
    id: 5,
    title: 'Security',
    description: 'Enterprise-grade security, compliance, and data protection solutions.',
    iconName: 'Shield',
    color: 'from-emerald-500 to-teal-600',
    delay: 0.4,
  },
  {
    id: 6,
    title: 'Analytics',
    description: 'Data-driven insights, performance metrics, and business intelligence.',
    iconName: 'BarChart3',
    color: 'from-indigo-500 to-violet-600',
    delay: 0.5,
  },
]

export const solutions = [
  {
    title: 'Enterprise Solutions',
    subtitle: 'Large-scale implementations',
    description: 'Robust solutions designed for enterprise organizations with complex requirements and global operations.',
    benefits: ['Scalable Architecture', 'Multi-tenant Support', 'Advanced Analytics', 'Enterprise Security'],
    gradient: 'from-blue-600 to-cyan-500',
  },
  {
    title: 'Startup Accelerator',
    subtitle: 'Growth-focused packages',
    description: 'Tailored services to help startups scale rapidly with cost-effective and flexible solutions.',
    benefits: ['Cost Optimization', 'Rapid Deployment', 'Flexible Scaling', 'Growth Mentoring'],
    gradient: 'from-cyan-500 to-teal-500',
  },
  {
    title: 'Digital Transformation',
    subtitle: 'Legacy to modern systems',
    description: 'Strategic modernization of legacy systems to unlock innovation and competitive advantages.',
    benefits: ['System Modernization', 'Process Automation', 'Data Migration', 'Staff Training'],
    gradient: 'from-teal-500 to-emerald-500',
  },
]

export const portfolioItems = [
  {
    id: 1,
    title: 'E-Commerce Platform',
    category: 'Web Development',
    description: 'A complete e-commerce solution with real-time inventory management and AI-powered recommendations.',
    image: 'https://images.unsplash.com/photo-1661956602116-aa6865609028?w=600&q=80',
    color: 'from-violet-600 to-indigo-600',
    size: 'large',
    tech: ['React', 'Node.js', 'MongoDB'],
  },
  {
    id: 2,
    title: 'FinTech Dashboard',
    category: 'UI/UX Design',
    description: 'Comprehensive financial analytics dashboard with real-time data visualization.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    color: 'from-cyan-500 to-blue-600',
    size: 'small',
    tech: ['D3.js', 'TypeScript'],
  },
  {
    id: 3,
    title: 'Healthcare App',
    category: 'Mobile Development',
    description: 'Patient management system with telemedicine integration.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=600&q=80',
    color: 'from-emerald-500 to-teal-600',
    size: 'small',
    tech: ['React Native', 'Firebase'],
  },
  {
    id: 4,
    title: 'AI Content Generator',
    category: 'Machine Learning',
    description: 'Advanced AI tool for generating marketing content, blog posts, and social media updates.',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80',
    color: 'from-purple-600 to-pink-600',
    size: 'medium',
    tech: ['Python', 'OpenAI', 'FastAPI'],
  },
  {
    id: 5,
    title: 'Smart Home IoT',
    category: 'IoT Solutions',
    description: 'Complete smart home ecosystem with voice control and automation.',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80',
    color: 'from-orange-500 to-red-500',
    size: 'medium',
    tech: ['Arduino', 'AWS IoT', 'Python'],
  },
  {
    id: 6,
    title: 'Blockchain Platform',
    category: 'Web3',
    description: 'Decentralized marketplace for digital assets and NFTs.',
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&q=80',
    color: 'from-amber-500 to-orange-600',
    size: 'large',
    tech: ['Solidity', 'Ethers.js', 'IPFS'],
  },
]

export const portfolioCategories = ['All', 'Web Development', 'UI/UX Design', 'Mobile Development', 'Machine Learning', 'IoT Solutions', 'Web3']

export const testimonials = [
  {
    name: 'Sarah Johnson',
    role: 'CEO, TechVision Inc',
    content: 'NEPTUNES TECH transformed our entire digital infrastructure. Their solutions are not just innovative but incredibly reliable. The team went above and beyond our expectations.',
    rating: 5,
    image: 'SJ',
    color: 'from-violet-500 to-purple-600',
  },
  {
    name: 'Michael Chen',
    role: 'CTO, Digital Innovators',
    content: 'The best technology partner we could ask for. Their expertise and commitment to excellence is unmatched in the industry. They delivered everything on time and under budget.',
    rating: 5,
    image: 'MC',
    color: 'from-cyan-500 to-blue-600',
  },
  {
    name: 'Emily Rodriguez',
    role: 'Founder, NextGen Solutions',
    content: 'Working with NEPTUNES TECH was a game-changer for our startup. They helped us scale from zero to hero in just months. Absolutely incredible team!',
    rating: 5,
    image: 'ER',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    name: 'David Thompson',
    role: 'VP Operations, Enterprise Co',
    content: 'Outstanding service, outstanding results. NEPTUNES TECH delivered exactly what we needed and more. They truly understand the enterprise landscape.',
    rating: 5,
    image: 'DT',
    color: 'from-orange-500 to-red-500',
  },
  {
    name: 'Lisa Wang',
    role: 'Product Director, InnovateTech',
    content: 'The attention to detail and creative problem-solving skills of the NEPTUNES TECH team are remarkable. They transformed our complex requirements into elegant solutions.',
    rating: 5,
    image: 'LW',
    color: 'from-pink-500 to-rose-600',
  },
  {
    name: 'James Miller',
    role: 'Managing Director, FutureCorp',
    content: "From concept to deployment, NEPTUNES TECH was with us every step of the way. Their proactive communication and technical prowess set them apart from the competition.",
    rating: 5,
    image: 'JM',
    color: 'from-indigo-500 to-violet-600',
  },
]

export const aboutFeatures = [
  {
    iconName: 'Zap',
    title: 'Lightning Fast',
    description: 'Optimized performance that keeps your business moving at digital speed',
    color: 'from-amber-500 to-orange-600',
  },
  {
    iconName: 'Shield',
    title: 'Enterprise Security',
    description: 'Bank-grade security protocols protecting your valuable data assets',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    iconName: 'Users',
    title: 'Expert Team',
    description: '150+ skilled professionals with diverse industry expertise',
    color: 'from-violet-500 to-purple-600',
  },
  {
    iconName: 'Award',
    title: 'Award Winning',
    description: 'Recognized excellence in digital transformation and innovation',
    color: 'from-cyan-500 to-blue-600',
  },
]

export const aboutStats = [
  { value: '500+', label: 'Projects Delivered', suffix: '' },
  { value: '98', label: 'Client Satisfaction', suffix: '%' },
  { value: '150', label: 'Team Members', suffix: '+' },
  { value: '10', label: 'Years Experience', suffix: '+' },
]

export const ctaStats = [
  { value: '500+', label: 'Active Clients' },
  { value: '1000+', label: 'Projects Delivered' },
  { value: '99.9%', label: 'Uptime SLA' },
]

export const footerLinks = {
  Product: [
    { label: 'Features', href: '#' },
    { label: 'Pricing', href: '#' },
    { label: 'Security', href: '#' },
    { label: 'Documentation', href: '#' },
  ],
  Company: [
    { label: 'About', href: '#about' },
    { label: 'Blog', href: '#' },
    { label: 'Careers', href: '#' },
    { label: 'Contact', href: '#contact' },
  ],
  Resources: [
    { label: 'Help Center', href: '#' },
    { label: 'API Docs', href: '#' },
    { label: 'Community', href: '#' },
    { label: 'Status', href: '#' },
  ],
  Legal: [
    { label: 'Privacy Policy', href: '/privacy-policy' },
    { label: 'Terms & Conditions', href: '/terms-and-conditions' },
    { label: 'Cookies', href: '#' },
    { label: 'Compliance', href: '#' },
  ],
}

export const socialLinks = [
  { iconName: 'Github', href: '#', label: 'GitHub' },
  { iconName: 'Linkedin', href: '#', label: 'LinkedIn' },
  { iconName: 'Twitter', href: '#', label: 'Twitter' },
  { iconName: 'Mail', href: '#', label: 'Email' },
]

export const companyInfo = {
  name: 'NEPTUNES TECH',
  tagline: 'Building tomorrow\'s technology solutions today. Innovative, reliable, scalable.',
  email: 'hello@neptunestech.com',
  phone: '+1 (555) 123-4567',
}

export const companyProjects = [
  {
    id: 1,
    name: 'Boat Track',
    description: 'Real-time tracking solution for boat fleet management and monitoring.',
    url: 'https://boat-track-989212354221.europe-west1.run.app/',
    gradient: 'from-blue-600 to-cyan-500',
    icon: 'Waves',
  },
  {
    id: 2,
    name: 'Mobility Platform',
    description: 'Advanced mobility solutions for transportation and logistics management.',
    url: 'https://mobility-dev-989212354221.europe-west1.run.app/',
    gradient: 'from-violet-600 to-purple-600',
    icon: 'Navigation',
  },
  {
    id: 3,
    name: 'Expense Management',
    description: 'Comprehensive expense tracking and financial management system.',
    url: 'https://expense-management-dev-989212354221.europe-west1.run.app/',
    gradient: 'from-emerald-500 to-teal-600',
    icon: 'TrendingUp',
  },
  {
    id: 4,
    name: 'EL Mec Elettronica',
    description: 'Quality control and manufacturing management system for electronics.',
    url: 'https://dev.qc.elmecelettronica.com/',
    gradient: 'from-orange-500 to-red-500',
    icon: 'Zap',
  },
  {
    id: 5,
    name: 'Oculus HC',
    description: 'Healthcare cloud platform with integrated medical data management.',
    url: 'https://oculus-hc-140209671642.us-central1.run.app/',
    gradient: 'from-pink-600 to-rose-500',
    icon: 'Heart',
  },
  {
    id: 6,
    name: 'Oculus EQ',
    description: 'Emotional intelligence and AI-powered analytics platform.',
    url: 'https://eq.oculusfx.ai/',
    gradient: 'from-indigo-600 to-purple-500',
    icon: 'Brain',
  },
  {
    id: 7,
    name: 'Oculus FX',
    description: 'Advanced trading and financial analysis platform with real-time insights.',
    url: 'https://oculusfx.ai/',
    gradient: 'from-cyan-600 to-blue-500',
    icon: 'BarChart3',
  },
  {
    id: 8,
    name: 'Fund Management',
    description: 'Complete fund portfolio management and investment tracking system.',
    url: 'https://fnd-dev-140209671642.us-central1.run.app/',
    gradient: 'from-amber-500 to-yellow-500',
    icon: 'Wallet',
  },
  {
    id: 9,
    name: 'BetStruck Admin',
    description: 'Administrative dashboard for sports betting platform management.',
    url: 'https://admin.betstruck.com/',
    gradient: 'from-red-600 to-pink-500',
    icon: 'Settings',
  },
  {
    id: 10,
    name: 'VMVM Korea',
    description: 'Korean enterprise platform with comprehensive business solutions.',
    url: 'http://vmvm.co.kr/',
    gradient: 'from-rose-500 to-red-600',
    icon: 'Globe',
  },
  {
    id: 11,
    name: 'Block Consult',
    description: 'Blockchain consulting and advisory services platform.',
    url: 'https://blockconsult.netlify.app/',
    gradient: 'from-purple-600 to-indigo-600',
    icon: 'Box',
  },
  {
    id: 12,
    name: 'Upper Level Sweeps',
    description: 'Premium sweepstakes and promotional campaign management.',
    url: 'https://upperlevelsweeps.com/',
    gradient: 'from-amber-500 to-orange-600',
    icon: 'Trophy',
  },
  {
    id: 13,
    name: 'Game Beroni',
    description: 'Interactive gaming platform with engaging user experiences.',
    url: 'https://game-beroni.netlify.app/',
    gradient: 'from-fuchsia-600 to-pink-600',
    icon: 'Gamepad2',
  },
  {
    id: 14,
    name: 'Litho Platform',
    description: 'Modern content management and digital publishing solution.',
    url: 'https://litho-329134440222.europe-west4.run.app/',
    gradient: 'from-slate-600 to-zinc-700',
    icon: 'Layers',
  },
  {
    id: 15,
    name: 'IJ-Hallen',
    description: 'Event management and venue booking platform.',
    url: 'https://ij-hallen-329134440222.europe-west4.run.app/',
    gradient: 'from-teal-500 to-cyan-600',
    icon: 'Calendar',
  },
  {
    id: 16,
    name: 'Elevatriq',
    description: 'Business elevation and growth consulting platform.',
    url: 'https://elevatriq.com/',
    gradient: 'from-sky-500 to-blue-600',
    icon: 'Rocket',
  },
  {
    id: 17,
    name: 'Vakantie Anders Beurs',
    description: 'Dutch travel and vacation fair booking platform.',
    url: 'https://www.vakantieandersbeurs.nl/',
    gradient: 'from-orange-500 to-amber-500',
    icon: 'Plane',
  },
  {
    id: 18,
    name: 'Trip Pearls',
    description: 'Travel discovery and booking platform for unique experiences.',
    url: 'https://trippearls.com/',
    gradient: 'from-emerald-500 to-green-600',
    icon: 'MapPin',
  },
  {
    id: 19,
    name: 'Clanic App',
    description: 'Community and clan management application.',
    url: 'https://clanic-app-zk5zju52ca-ez.a.run.app/',
    gradient: 'from-violet-500 to-purple-600',
    icon: 'Users',
  },
  {
    id: 20,
    name: 'Bureau Platform',
    description: 'Professional services and bureau management system.',
    url: 'https://bureau-329134440222.europe-west4.run.app/',
    gradient: 'from-blue-600 to-indigo-600',
    icon: 'Building2',
  },
  {
    id: 21,
    name: 'Provincie Deals',
    description: 'Dutch provincial deals and local offers marketplace.',
    url: 'https://provinciedeals.nl/',
    gradient: 'from-red-500 to-rose-600',
    icon: 'Tag',
  },
  {
    id: 22,
    name: 'TestAlly',
    description: 'Comprehensive testing and QA automation platform.',
    url: 'https://testally.com/',
    gradient: 'from-green-500 to-emerald-600',
    icon: 'CheckCircle',
  },
  {
    id: 23,
    name: 'Hourly4U',
    description: 'Hourly services and freelance marketplace platform.',
    url: 'https://hourly4u.com/',
    gradient: 'from-cyan-500 to-teal-600',
    icon: 'Clock',
  },
  {
    id: 24,
    name: 'WGP Plaza',
    description: 'Commercial plaza and retail management system.',
    url: 'https://wgpplaza.com/home',
    gradient: 'from-indigo-500 to-blue-600',
    icon: 'Store',
  },
  {
    id: 25,
    name: 'TenStat',
    description: 'Statistical analysis and data insights platform.',
    url: 'https://www.hugedomains.com/domain_profile.cfm?d=tenstat.com',
    gradient: 'from-purple-500 to-violet-600',
    icon: 'PieChart',
  },
  {
    id: 26,
    name: 'FMS New',
    description: 'Fleet management system with real-time tracking.',
    url: 'https://fms-new-zk5zju52ca-ez.a.run.app/',
    gradient: 'from-blue-500 to-cyan-500',
    icon: 'Truck',
  },
  {
    id: 27,
    name: 'DiSearch AI',
    description: 'AI-powered search and discovery application.',
    url: 'https://apps.disearch.ai/',
    gradient: 'from-pink-500 to-rose-500',
    icon: 'Search',
  },
  {
    id: 28,
    name: 'Foresight App',
    description: 'Predictive analytics and business forecasting tool.',
    url: 'https://foresight-app-140209671642.us-central1.run.app/',
    gradient: 'from-amber-600 to-yellow-500',
    icon: 'Eye',
  },
  {
    id: 29,
    name: 'Sneakers Dev',
    description: 'Sneaker marketplace and collection management platform.',
    url: 'https://sneakers-dev-84543727897.europe-west4.run.app/',
    gradient: 'from-gray-700 to-slate-600',
    icon: 'ShoppingBag',
  },
  {
    id: 30,
    name: 'Dutch Software Solutions',
    description: 'Custom software development and IT consulting services.',
    url: 'https://www.dutchsoftwaresolutions.com/',
    gradient: 'from-orange-600 to-red-500',
    icon: 'Code2',
  },
  {
    id: 31,
    name: 'Camper Platform',
    description: 'Camper rental and outdoor adventure booking system.',
    url: 'https://camper-329134440222.europe-west4.run.app/',
    gradient: 'from-green-600 to-teal-500',
    icon: 'Tent',
  },
  {
    id: 32,
    name: 'Denlop App',
    description: 'Modern application development and deployment platform.',
    url: 'https://denol-app-329134440222.europe-west4.run.app/',
    gradient: 'from-blue-500 to-indigo-600',
    icon: 'Layout',
  },
  {
    id: 33,
    name: 'Camper Dev',
    description: 'Camper development and testing environment.',
    url: 'https://camper-dev-329134440222.europe-west4.run.app/',
    gradient: 'from-lime-500 to-green-600',
    icon: 'Car',
  },
  {
    id: 34,
    name: 'Food App',
    description: 'Food ordering and delivery management platform.',
    url: 'https://food-app-dev-329134440222.europe-west4.run.app/',
    gradient: 'from-orange-500 to-red-500',
    icon: 'UtensilsCrossed',
  },
  {
    id: 35,
    name: 'Bike Shop',
    description: 'Online bicycle store and rental management system.',
    url: 'https://bike-shop-dev-329134440222.europe-west4.run.app/',
    gradient: 'from-yellow-500 to-orange-500',
    icon: 'Bike',
  },
  {
    id: 36,
    name: 'FMS Test',
    description: 'Faculty management system testing environment.',
    url: 'https://fms-test-bdqbukgwtq-ez.a.run.app/',
    gradient: 'from-indigo-500 to-purple-600',
    icon: 'GraduationCap',
  },
  {
    id: 37,
    name: 'Pokedeck',
    description: 'Pokemon card collection and deck building application.',
    url: 'https://pokedeck-814235293098.europe-west4.run.app/',
    gradient: 'from-yellow-400 to-red-500',
    icon: 'Sparkles',
  },
  {
    id: 38,
    name: 'Villa Rental Provinciedeals',
    description: 'Premium villa rental marketplace for provincial deals.',
    url: 'https://villa-rental-provinciedeals-329134440222.europe-west4.run.app/',
    gradient: 'from-rose-500 to-pink-600',
    icon: 'Home',
  },
  {
    id: 39,
    name: 'Villa Rental',
    description: 'Luxury villa rental and vacation property platform.',
    url: 'https://villa-rental-zk5zju52ca-ez.a.run.app/',
    gradient: 'from-amber-500 to-orange-600',
    icon: 'Building',
  },
  {
    id: 40,
    name: 'Padel City',
    description: 'Padel court booking and sports facility management.',
    url: 'https://padel-city-329134440222.europe-west4.run.app/',
    gradient: 'from-green-500 to-emerald-600',
    icon: 'Trophy',
  },
]

export const termsData = [
  {
    id: 'acceptance',
    iconName: 'FileText',
    title: 'Acceptance of Terms',
    content: [
      'By accessing and using the NEPTUNES TECH website and services, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.',
      'If you do not agree with any part of these terms, you must not use our website or services.',
      'We reserve the right to modify these terms at any time. Your continued use of our services after any changes constitutes acceptance of the new terms.',
      'It is your responsibility to review these Terms and Conditions periodically for any updates or changes.',
    ],
  },
  {
    id: 'services',
    iconName: 'Globe',
    title: 'Description of Services',
    content: [
      'NEPTUNES TECH provides technology solutions including web development, mobile application development, cloud solutions, AI integration, security services, and analytics.',
      'Our services are subject to change without prior notice. We continuously strive to improve and expand our offerings to meet your needs.',
      'Service availability may vary based on your location, and some services may require additional agreements or subscriptions.',
      'We reserve the right to discontinue any service at our discretion with reasonable notice to affected clients.',
    ],
  },
  {
    id: 'user-obligations',
    iconName: 'Users',
    title: 'User Obligations',
    content: [
      'You agree to use our services only for lawful purposes and in accordance with these Terms and Conditions.',
      'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.',
      'You must not attempt to gain unauthorized access to any part of our systems, networks, or data.',
      'You agree not to reproduce, duplicate, copy, sell, resell, or exploit any portion of our services without express written permission.',
      'You must provide accurate and complete information when creating an account or engaging our services.',
    ],
  },
  {
    id: 'intellectual-property',
    iconName: 'Shield',
    title: 'Intellectual Property Rights',
    content: [
      'All content, features, and functionality on our website, including but not limited to text, graphics, logos, icons, images, audio clips, digital downloads, and software, are the exclusive property of NEPTUNES TECH.',
      'Our trademarks, service marks, and logos may not be used in connection with any product or service without prior written consent.',
      'You are granted a limited, non-exclusive, non-transferable license to access and use our services for personal or business purposes.',
      'Any unauthorized use of our intellectual property may result in legal action and termination of your access to our services.',
    ],
  },
  {
    id: 'privacy',
    iconName: 'Shield',
    title: 'Privacy and Data Protection',
    content: [
      'Your privacy is important to us. Our collection and use of personal information is governed by our Privacy Policy.',
      'We implement industry-standard security measures to protect your data from unauthorized access, disclosure, or destruction.',
      'By using our services, you consent to the collection, use, and sharing of your information as described in our Privacy Policy.',
      'We comply with applicable data protection laws and regulations, including GDPR where applicable.',
      'You have the right to access, correct, or delete your personal information in accordance with applicable laws.',
    ],
  },
  {
    id: 'liability',
    iconName: 'AlertTriangle',
    title: 'Limitation of Liability',
    content: [
      'NEPTUNES TECH shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use or inability to use our services.',
      'Our total liability for any claims arising from these terms or your use of our services shall not exceed the amount paid by you for our services in the twelve (12) months preceding the claim.',
      'We do not guarantee that our services will be uninterrupted, timely, secure, or error-free.',
      'Some jurisdictions do not allow the exclusion of certain warranties or limitations of liability, so some of the above limitations may not apply to you.',
    ],
  },
  {
    id: 'indemnification',
    iconName: 'Scale',
    title: 'Indemnification',
    content: [
      'You agree to indemnify, defend, and hold harmless NEPTUNES TECH, its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt arising from:',
      '• Your use of and access to our services',
      '• Your violation of any term of these Terms and Conditions',
      '• Your violation of any third-party rights, including intellectual property rights',
      '• Any claim that your content or actions caused damage to a third party',
    ],
  },
  {
    id: 'termination',
    iconName: 'AlertTriangle',
    title: 'Termination',
    content: [
      'We may terminate or suspend your access to our services immediately, without prior notice or liability, for any reason, including breach of these Terms and Conditions.',
      'Upon termination, your right to use our services will immediately cease.',
      'All provisions of these Terms which by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, indemnity, and limitations of liability.',
      'You may terminate your account at any time by contacting us or through your account settings.',
    ],
  },
  {
    id: 'governing-law',
    iconName: 'Scale',
    title: 'Governing Law',
    content: [
      'These Terms and Conditions shall be governed by and construed in accordance with the laws of the jurisdiction in which NEPTUNES TECH operates.',
      'Any disputes arising from these terms shall be resolved through binding arbitration or in the courts of competent jurisdiction.',
      'You agree to submit to the personal jurisdiction of the courts located within the governing jurisdiction.',
      'The failure of NEPTUNES TECH to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.',
    ],
  },
  {
    id: 'contact',
    iconName: 'Mail',
    title: 'Contact Information',
    content: [
      'If you have any questions about these Terms and Conditions, please contact us:',
      '• Email: legal@neptunestech.com',
      '• Address: NEPTUNES TECH Headquarters',
      '• Website: www.neptunestech.com',
      'We aim to respond to all inquiries within 2-3 business days.',
    ],
  },
]

export const privacyData = [
  {
    id: 'introduction',
    iconName: 'Shield',
    title: 'Introduction',
    content: [
      'This Privacy Policy explains how Neptunes Tech collects, uses, and protects your information when you use our website and services.',
      'We are committed to ensuring that your privacy is protected. Any information you provide will be used in accordance with this privacy statement.',
      'We may update this policy from time to time by updating this page. You should check this page periodically to ensure you are happy with any changes.',
    ],
  },
  {
    id: 'information-collect',
    iconName: 'Database',
    title: 'Information We Collect',
    content: [
      'We may collect personal information such as your name, email address, phone number, and project details when you contact us, submit a form, or request a consultation.',
      'We also collect:',
      '• Technical data including IP address, browser type, and device information',
      '• Usage data about how you interact with our website',
      '• Communication records when you contact us via email or forms',
      '• Any other information you choose to provide to us',
    ],
  },
  {
    id: 'how-we-use',
    iconName: 'Eye',
    title: 'How We Use Your Information',
    content: [
      'The information we collect may be used to:',
      '• Respond to inquiries or project requests',
      '• Provide software development or consulting services',
      '• Improve our website and services',
      '• Communicate with clients about projects or updates',
      '• Send periodic emails regarding your projects or other services',
      '• Analyze website usage to enhance user experience',
    ],
  },
  {
    id: 'data-protection',
    iconName: 'Lock',
    title: 'Data Protection',
    content: [
      'Neptunes Tech takes appropriate security measures to protect your personal information from unauthorized access, disclosure, or misuse.',
      'We implement a variety of security measures including:',
      '• Secure SSL encryption for data transmission',
      '• Regular security assessments and updates',
      '• Limited access to personal information by authorized personnel only',
      '• Secure data storage with encryption at rest',
      'However, no method of transmission over the Internet is 100% secure, and we cannot guarantee absolute security.',
    ],
  },
  {
    id: 'third-party',
    iconName: 'Users',
    title: 'Third Party Services',
    content: [
      'Our website may use third-party tools such as analytics services or advertising platforms which may collect anonymous usage data to improve user experience.',
      'These third-party services have their own privacy policies addressing how they use such information.',
      'Third-party services we may use include:',
      '• Google Analytics for website traffic analysis',
      '• Payment processors for billing purposes',
      '• Cloud hosting providers for service delivery',
      'We encourage you to review the privacy policies of these third parties.',
    ],
  },
  {
    id: 'data-sharing',
    iconName: 'Share2',
    title: 'Data Sharing',
    content: [
      'We do not sell, trade, or share your personal information with third parties except when required to deliver services or comply with legal obligations.',
      'We may share your information in the following circumstances:',
      '• With service providers who assist in our operations',
      '• When required by law or legal process',
      '• To protect our rights, privacy, safety, or property',
      '• In connection with a merger, acquisition, or sale of assets',
      'Any third parties with whom we share data are obligated to protect your information.',
    ],
  },
  {
    id: 'cookies',
    iconName: 'Database',
    title: 'Cookies & Tracking',
    content: [
      'Our website may use cookies and similar tracking technologies to enhance your browsing experience.',
      'Cookies are small files stored on your device that help us:',
      '• Remember your preferences and settings',
      '• Understand how you use our website',
      '• Improve our services based on your interactions',
      '• Provide personalized content and recommendations',
      'You can choose to disable cookies through your browser settings, though this may affect website functionality.',
    ],
  },
  {
    id: 'your-rights',
    iconName: 'CheckCircle',
    title: 'Your Rights',
    content: [
      'You have certain rights regarding your personal information:',
      '• Right to access: Request a copy of your personal data',
      '• Right to rectification: Request correction of inaccurate data',
      '• Right to erasure: Request deletion of your personal data',
      '• Right to restrict processing: Limit how we use your data',
      '• Right to data portability: Receive your data in a portable format',
      '• Right to object: Object to certain types of processing',
      'To exercise any of these rights, please contact us using the information below.',
    ],
  },
  {
    id: 'consent',
    iconName: 'CheckCircle',
    title: 'Your Consent',
    content: [
      'By using this website, you consent to our privacy policy and the collection of information described above.',
      'You may withdraw your consent at any time by contacting us, though this may affect our ability to provide certain services.',
      'Continued use of our website after any changes to this policy constitutes acceptance of those changes.',
    ],
  },
  {
    id: 'contact',
    iconName: 'Mail',
    title: 'Contact Us',
    content: [
      'If you have any questions regarding this Privacy Policy, please contact us through the contact form on our website.',
      '• Email: privacy@neptunestech.com',
      '• Website: www.neptunestech.com/contact',
      '• Address: NEPTUNES TECH Headquarters',
      'We aim to respond to all privacy-related inquiries within 48 hours.',
    ],
  },
]
